### ISSUE TITLE
Feature request: differentiate selected/unselected windows by border color

### ISSUE THREAD

**Issue by boomlinde** [gboncoffee/iguassu#1]
Plan 9 rio draws the selected window border using `DGreygreen` (0x55AAAAFF)  and unselected window borders using `DPalegreygreen` (0x9EEEEEFF). Implementing similar functionality in Iguassu would make it easier to determine which window is currently selected.

**Comment by gboncoffee** [comment]
Neat! It'll probably be very simple to implement. I'll try to do it this night (UTC -3) as I got some Uni work to do. Thanks for the suggestion!

**Comment by gboncoffee** [comment]
Added!
